def print_args(args):
    print("\033[1mBasic Config\033[0m")
    print(f'  {"Task Name:":<20}{args.task_name:<20}{"Is Training:":<20}{args.is_training:<20}')
    print(f'  {"Model ID:":<20}{args.model_id:<20}{"Model:":<20}{args.model:<20}')
    print()

    print("\033[1mData Loader\033[0m")
    print(f'  {"Data:":<20}{args.data:<20}{"Root Path:":<20}{args.root_path:<20}')
    print(f'  {"Data Path:":<20}{args.data_path:<20}{"Features:":<20}{args.features:<20}')
    print(f'  {"Target:":<20}{args.target:<20}{"Freq:":<20}{args.freq:<20}')
    print(f'  {"Checkpoints:":<20}{args.checkpoints:<20}')
    print()

    print("\033[1mForecasting Task\033[0m")
    print(f'  {"Seq Len:":<20}{args.seq_len:<20}{"Label Len:":<20}{args.label_len:<20}')
    print(f'  {"Pred Len:":<20}{args.pred_len:<20}{"Inverse:":<20}{args.inverse:<20}')
    print()

    print("\033[1mEATA Parameters\033[0m")
    print(f'  {"Enc In:":<20}{args.enc_in:<20}{"d Model:":<20}{args.d_model:<20}')
    print(f'  {"Dropout:":<20}{args.dropout:<20}{"K Lookback:":<20}{args.k_lookback:<20}')
    print(f'  {"Method:":<20}{args.method:<20}{"Hidden:":<20}{args.hidden:<20}')
    print(f'  {"Bias:":<20}{args.bias:<20}{"Interact:":<20}{args.interact:<20}')
    print()

    print("\033[1mRun Parameters\033[0m")
    print(f'  {"Num Workers:":<20}{args.num_workers:<20}{"Itr:":<20}{args.itr:<20}')
    print(f'  {"Train Epochs:":<20}{args.train_epochs:<20}{"Batch Size:":<20}{args.batch_size:<20}')
    print(f'  {"Patience:":<20}{args.patience:<20}{"Learning Rate:":<20}{args.learning_rate:<20}')
    print(f'  {"Des:":<20}{args.des:<20}{"Lradj:":<20}{args.lradj:<20}')
    print(f'  {"Use Amp:":<20}{args.use_amp:<20}')
    print()

    print("\033[1mDevice\033[0m")
    print(f'  {"Use GPU:":<20}{args.use_gpu:<20}{"GPU:":<20}{args.gpu:<20}')
    print(f'  {"GPU Type:":<20}{args.gpu_type:<20}')
    print()
